### ISSUE TITLE
Does this plugin work?

### ISSUE THREAD

**Issue by dt1973** [liuxuanzy/jquery-backgroundfix#1]
Unable to make this plugin work. Would appreciate some feedback:

http://jsbin.com/ripegiqose/1/edit

Thanks!

**Comment by liuxuanzy** [comment]
This is used for $.fn.css and $.fn.animate.

**Comment by liuxuanzy** [comment]
@dt1973  it can't effect in .css files

**Comment by dt1973** [comment]
Ah, ok. I thought it was similar to cssFx, Autoprefixer etc.

Thanks for letting me know!
